services:
  mongo:
    image: mongo:7
    container_name: library_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: library
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --username mongo_admin --password password --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: library_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: library_api
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://mongo_admin:password@mongo:27017/?authSource=admin
      MONGODB_DB: library
      MONGODB_BOOKS_COLLECTION: books
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mongo_data:
